### ISSUE TITLE
[Crash]: Crash during initialization

### ISSUE THREAD

**Issue by Atmxsz** [Fuzss/resourcepackoverrides#1]
### Mod Loader (Required)

Forge 36.2.39

### Minecraft Version (Required)

1.16.5

### Mod Version (Required)

1.0.1

### Notes (Required)

Note: Conflict with Remove Reloading Screen. I am reporting this problem to the developers of both mods.

1. Run Minecraft.
2. Exit with code 1.

There is no crash report.

### Crash Report (Required)

https://gist.github.com/Atmxsz/3e92c72d89a7d9f37cdf3ace33a44380

**Comment by Fuzss** [comment]
Thanks for reporting, that’s not on my end. Left a comment on the other issue.
