### ISSUE TITLE
[Suggestion]: Debug key to revert to defined default resource pack list and order

### ISSUE THREAD

**Issue by TBlazeWarriorT** [Fuzss/resourcepackoverrides#10]
### Suggestion (Required)

I've just setup my default_packs list, but my in-game resource pack list is all messed up and I have no easy way to revert it back to the ideal default I've just defined. Let's say I mess something up on the ordering in the future or etc etc, it would also be very ideal to have a button to apply my defined default packs.

So the suggestion is something like having a Debug Key like "Hold 'T' to reset your resource pack selection to your default packs"

**Comment by Fuzss** [comment]
Added in v20.4.0.

**Comment by HB-Stratos** [comment]
A backport of this feature to 1.20.1/v8.0.3 would be appreciated.
