### ISSUE TITLE
[Bug]: overrides related to rejected curseforge modpack

### ISSUE THREAD

**Issue by corbinpenguin** [Fuzss/resourcepackoverrides#17]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

V8.0.3

### Notes (Required)

I tried to use resourcepack overrides but for one my changed in the config seemed to only work once, then when I relaunched the game they didn't work again.

Regardless, when I went to upload the modpack to curseforge I encountered an issue where the resourcepacks I had done things with in the config for this mod should be referenced in a manifest.json instead of being added directly to a zip file.

After this I decided to uninstall the mod, delete the config, and then reinstalled the resource packs just to be safe. 
After that I tried to upload the modpack again, and got a different error that also mentions "overrides/" and I am just so confused.

I just want to upload my modpack and I can't if it keeps getting rejected because of this
![Screenshot_20240724-141239](https://github.com/user-attachments/assets/57b5f398-290b-4bda-9c9e-12501b7990df)
![Screenshot_20240724-082149](https://github.com/user-attachments/assets/c2277575-f154-4cac-a444-2e856b7f73fb)

### latest.log (Required)

This issue doesn't have a lot associated with it

**Comment by Fuzss** [comment]
Wrong mod mate, Resource Pack Overrides does not add the `overrides` directory.
Here is an outline what it does: https://github.com/Fuzss/resourcepackoverrides/blob/main/README.md
