### ISSUE TITLE
[Bug]: Fabric Mods resourcepack id does not work.

### ISSUE THREAD

**Issue by vos6434** [Fuzss/resourcepackoverrides#3]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.0

### Notes (Required)

Using Fabric Mods resourcepack id in the config does not show any result in game.

for example, settings Fabric Mods to hide does not hide the resourcepack in game.

[config used](https://gist.github.com/vos6434/628d7069aecb7a41891a2b17d952eb53)

**Comment by Fuzss** [comment]
So the internal fabric pack id seems to have changed to `fabric` from `Fabric Mods` (not sure when, definitely was `Fabric Mods` in 1.19.2 when this mod was developed), also you cannot include comments in `.json`, those will break the file. I've just updated to README with all that.
