### ISSUE TITLE
[Bug]: Order buttons shown when all but one packs are hidden

### ISSUE THREAD

**Issue by vos6434** [Fuzss/resourcepackoverrides#4]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.0

### Notes (Required)

Resourepack order buttons are shown even though custom resourcepacks are hidden. This could cause confusion if a player moves vanilla on top of the modpack's resourcepack.
![2023-08-05_17 26 26](https://github.com/Fuzss/resourcepackoverrides/assets/21976486/2bef4bcc-9ddb-42e7-a189-62c34b9f6d13)

**Comment by Fuzss** [comment]
Thanks, fixed in v8.0.1.
