### ISSUE TITLE
[Suggestion]: Translatable title text

### ISSUE THREAD

**Issue by Disketaa** [Fuzss/resourcepackoverrides#7]
### Suggestion (Required)

I don't know if this is already doable, but can I change resourcepack name to translatable string? 
I didn't found discord or something server to ask, so, sorry for spamming me here

```
  "pack_overrides": {
      "vanilla": {
      "title": "\"Something\"",
      "description": "\"Resource pack from Minecraft\""
    }
```

Can I somehow replace somehow `"title": "\"Something\"",` with `"title": "item.minecraft.apple"` (for example)

**Comment by Fuzss** [comment]
https://minecraft.wiki/w/Raw_JSON_text_format#Translated_Text

**Comment by Disketaa** [comment]
thx

**Comment by Disketaa** [comment]
hmm still can't figure out how to make it

```
      "vanilla": {
        "title": { 
          "translate": "item.minecraft.apple" 
        },
        "description": "\"Resource pack from Minecraft\""
    },
```

or 

```
  "pack_overrides": {
      "vanilla": {
      "title": "item.minecraft.apple",
      "description": "\"Resource pack from Minecraft\""
    },
```

not working 😅

**Comment by Fuzss** [comment]
`"title": "{\"translate\":\"item.minecraft.apple\"}"`

**Comment by Disketaa** [comment]
Yay, so much thanks! You can delete this issue by the way, just to not interfere too much
